version: '2'

services:
  web-pdf-toolbox:
    restart: always
    container_name: "${PROJECT_NAME}_main"
    hostname: web-pdf-toolbox
    image: zpex/web-pdf-toolbox:latest
    ports:
      - "${HTTP_IP}:${HTTP_PORT}:80"
    environment:
      - TZ=${TZ}

    volumes:
      - "${DATA_FOLDER_PATH}/pdf/:/tmp/pdf/"
    restart: always


